[base]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags =
  -std=gnu++2a
  -Isrc/page/include
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DEINK_DISPLAY_SINGLE_BUFFER_MODE=1
  -Wl,--wrap=esp_pm_lock_create,--wrap=esp_pm_lock_acquire,--wrap=esp_pm_lock_release,--wrap=esp_pm_lock_delete

build_unflags =
  -std=gnu++11

board_build.flash_mode = dio
board_build.flash_size = 16MB

lib_deps =
  BoardConfig=symlink://freeink/libs/hardware/BoardConfig
  EInkDisplay=symlink://freeink/libs/display/FreeInkDisplay
  InputManager=symlink://freeink/libs/hardware/InputManager
  BatteryMonitor=symlink://freeink/libs/hardware/BatteryMonitor
  PowerManager=symlink://freeink/libs/hardware/PowerManager
  RecoveryBoot=symlink://freeink/libs/hardware/RecoveryBoot
  SDCardManager=symlink://freeink/libs/hardware/SDCardManager
  XteinkDetect=symlink://freeink/libs/hardware/XteinkDetect
  Icons=symlink://freeink/libs/assets/Icons
  FreeInkUI=symlink://freeink/libs/ui/FreeInkUI
  h2zero/NimBLE-Arduino@^2.3.8

[platformio]
default_envs = x4pro

[env:xteink]
extends = base
board = esp32-c3-devkitm-1
custom_component_remove =
  espressif/esp_insights
  espressif/esp_rainmaker
lib_ignore =
  Insights
  RainMaker
extra_scripts =
  pre:scripts/fix_freertos_linker.py
build_flags =
  ${base.build_flags}
  -DFREEINK_DEVICE_X3=1
  -DFREEINK_DEVICE_X4=1
custom_sdkconfig =
  CONFIG_ARDUINO_SELECTIVE_COMPILATION=y
  '# CONFIG_ARDUINO_SELECTIVE_ArduinoOTA is not set'
  '# CONFIG_ARDUINO_SELECTIVE_AsyncUDP is not set'
  '# CONFIG_ARDUINO_SELECTIVE_BLE is not set'
  '# CONFIG_ARDUINO_SELECTIVE_BluetoothSerial is not set'
  '# CONFIG_ARDUINO_SELECTIVE_DNSServer is not set'
  '# CONFIG_ARDUINO_SELECTIVE_EEPROM is not set'
  '# CONFIG_ARDUINO_SELECTIVE_ESP_SR is not set'
  '# CONFIG_ARDUINO_SELECTIVE_Ethernet is not set'
  '# CONFIG_ARDUINO_SELECTIVE_FFat is not set'
  '# CONFIG_ARDUINO_SELECTIVE_FS is not set'
  '# CONFIG_ARDUINO_SELECTIVE_Hash is not set'
  '# CONFIG_ARDUINO_SELECTIVE_HTTPClient is not set'
  '# CONFIG_ARDUINO_SELECTIVE_LittleFS is not set'
  '# CONFIG_ARDUINO_SELECTIVE_Matter is not set'
  '# CONFIG_ARDUINO_SELECTIVE_NetBIOS is not set'
  '# CONFIG_ARDUINO_SELECTIVE_Network is not set'
  '# CONFIG_ARDUINO_SELECTIVE_NetworkClientSecure is not set'
  '# CONFIG_ARDUINO_SELECTIVE_OpenThread is not set'
  '# CONFIG_ARDUINO_SELECTIVE_PPP is not set'
  CONFIG_ARDUINO_SELECTIVE_Preferences=y
  '# CONFIG_ARDUINO_SELECTIVE_RainMaker is not set'
  '# CONFIG_ARDUINO_SELECTIVE_SD is not set'
  '# CONFIG_ARDUINO_SELECTIVE_SD_MMC is not set'
  CONFIG_ARDUINO_SELECTIVE_SPI=y
  '# CONFIG_ARDUINO_SELECTIVE_SPIFFS is not set'
  '# CONFIG_ARDUINO_SELECTIVE_SimpleBLE is not set'
  '# CONFIG_ARDUINO_SELECTIVE_Ticker is not set'
  '# CONFIG_ARDUINO_SELECTIVE_Update is not set'
  '# CONFIG_ARDUINO_SELECTIVE_WebServer is not set'
  '# CONFIG_ARDUINO_SELECTIVE_WiFi is not set'
  '# CONFIG_ARDUINO_SELECTIVE_WiFiProv is not set'
  CONFIG_ARDUINO_SELECTIVE_Wire=y
  '# CONFIG_ARDUINO_SELECTIVE_Zigbee is not set'
  '# CONFIG_ARDUINO_SELECTIVE_Insights is not set'
  CONFIG_PM_ENABLE=y
  CONFIG_PM_DFS_INIT_AUTO=y
  CONFIG_PM_PROFILING=y
  CONFIG_PM_LIGHT_SLEEP_CALLBACKS=y
  CONFIG_FREERTOS_USE_TICKLESS_IDLE=y
  CONFIG_FREERTOS_EXPECTED_IDLE_TIME_BEFORE_SLEEP=3
  CONFIG_FREERTOS_USE_TRACE_FACILITY=y
  CONFIG_FREERTOS_USE_STATS_FORMATTING_FUNCTIONS=y
  CONFIG_FREERTOS_GENERATE_RUN_TIME_STATS=y
  CONFIG_FREERTOS_RUN_TIME_STATS_USING_ESP_TIMER=y
  CONFIG_FREERTOS_PLACE_FUNCTIONS_INTO_FLASH=y
  CONFIG_ESP_TIMER_PROFILING=y
  CONFIG_BT_ENABLED=y
  CONFIG_BT_CTRL_MODEM_SLEEP=y
  CONFIG_BT_CTRL_MODEM_SLEEP_MODE_1=y
  CONFIG_BT_CTRL_LPCLK_SEL_MAIN_XTAL=y
  CONFIG_BT_CTRL_MAIN_XTAL_PU_DURING_LIGHT_SLEEP=y
  '# CONFIG_RTC_CLK_SRC_INT_RC is not set'
  CONFIG_RTC_CLK_SRC_INT_8MD256=y
  CONFIG_RTC_CLK_CAL_CYCLES=3000

[env:x4pro]
extends = base
board = esp32-s3-devkitc1-n16r8
board_build.mcu = esp32s3
build_flags =
  ${base.build_flags}
  -DBOARD_HAS_PSRAM
  -DFREEINK_DEVICE_X4PRO=1
  -DUSE_BLOCK_DEVICE_INTERFACE=1
custom_component_remove =
  espressif/esp_insights
  espressif/esp_rainmaker
lib_ignore =
  Insights
  RainMaker
  ESP_SR
custom_sdkconfig =
  CONFIG_ARDUINO_SELECTIVE_COMPILATION=y
  '# CONFIG_ARDUINO_SELECTIVE_ArduinoOTA is not set'
  '# CONFIG_ARDUINO_SELECTIVE_AsyncUDP is not set'
  '# CONFIG_ARDUINO_SELECTIVE_BLE is not set'
  '# CONFIG_ARDUINO_SELECTIVE_BluetoothSerial is not set'
  '# CONFIG_ARDUINO_SELECTIVE_DNSServer is not set'
  '# CONFIG_ARDUINO_SELECTIVE_EEPROM is not set'
  '# CONFIG_ARDUINO_SELECTIVE_ESP_SR is not set'
  '# CONFIG_ARDUINO_SELECTIVE_Ethernet is not set'
  '# CONFIG_ARDUINO_SELECTIVE_FFat is not set'
  '# CONFIG_ARDUINO_SELECTIVE_FS is not set'
  '# CONFIG_ARDUINO_SELECTIVE_Hash is not set'
  '# CONFIG_ARDUINO_SELECTIVE_HTTPClient is not set'
  '# CONFIG_ARDUINO_SELECTIVE_LittleFS is not set'
  '# CONFIG_ARDUINO_SELECTIVE_Matter is not set'
  '# CONFIG_ARDUINO_SELECTIVE_NetBIOS is not set'
  '# CONFIG_ARDUINO_SELECTIVE_Network is not set'
  '# CONFIG_ARDUINO_SELECTIVE_NetworkClientSecure is not set'
  '# CONFIG_ARDUINO_SELECTIVE_OpenThread is not set'
  '# CONFIG_ARDUINO_SELECTIVE_PPP is not set'
  CONFIG_ARDUINO_SELECTIVE_Preferences=y
  '# CONFIG_ARDUINO_SELECTIVE_RainMaker is not set'
  '# CONFIG_ARDUINO_SELECTIVE_SD is not set'
  CONFIG_ARDUINO_SELECTIVE_SD_MMC=y
  CONFIG_ARDUINO_SELECTIVE_SPI=y
  '# CONFIG_ARDUINO_SELECTIVE_SPIFFS is not set'
  '# CONFIG_ARDUINO_SELECTIVE_SimpleBLE is not set'
  '# CONFIG_ARDUINO_SELECTIVE_Ticker is not set'
  '# CONFIG_ARDUINO_SELECTIVE_Update is not set'
  '# CONFIG_ARDUINO_SELECTIVE_WebServer is not set'
  '# CONFIG_ARDUINO_SELECTIVE_WiFi is not set'
  '# CONFIG_ARDUINO_SELECTIVE_WiFiProv is not set'
  CONFIG_ARDUINO_SELECTIVE_Wire=y
  '# CONFIG_ARDUINO_SELECTIVE_Zigbee is not set'
  '# CONFIG_ARDUINO_SELECTIVE_Insights is not set'
  CONFIG_PM_ENABLE=y
  CONFIG_PM_DFS_INIT_AUTO=y
  CONFIG_PM_PROFILING=y
  CONFIG_PM_LIGHT_SLEEP_CALLBACKS=y
  CONFIG_PM_POWER_DOWN_CPU_IN_LIGHT_SLEEP=y
  CONFIG_FREERTOS_USE_TICKLESS_IDLE=y
  CONFIG_FREERTOS_EXPECTED_IDLE_TIME_BEFORE_SLEEP=3
  CONFIG_FREERTOS_USE_TRACE_FACILITY=y
  CONFIG_FREERTOS_USE_STATS_FORMATTING_FUNCTIONS=y
  CONFIG_FREERTOS_GENERATE_RUN_TIME_STATS=y
  CONFIG_FREERTOS_RUN_TIME_STATS_USING_ESP_TIMER=y
  CONFIG_FREERTOS_PLACE_FUNCTIONS_INTO_FLASH=y
  CONFIG_ESP_TIMER_PROFILING=y
  CONFIG_BT_ENABLED=y
  CONFIG_BT_CTRL_MODEM_SLEEP=y
  CONFIG_BT_CTRL_MODEM_SLEEP_MODE_1=y
  CONFIG_BT_CTRL_MAIN_XTAL_PU_DURING_LIGHT_SLEEP=y
